name: CI/CD Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 45.77.155.192
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/**"
          target: "/var/www/html"
